[workspace]

members = [
    "shared",
    "moeche",
    "wheel_builder",
    "wheel_compiler",
    "examples/simple_pkg",
#   "rust_lexer",
#    "rust_parser",
    "pyo3_bindgen",
#    "harness_gen",
]